service:
  name: sls-TS-api-call

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom: 
  secrets: ${file(./.secrets.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    GOOGLE_PLACES_KEY: ${self:custom.secrets.GOOGLE_PLACES_KEY}

profile: serverless-aws-admin

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
