service:
  name: sls-TS-api-call

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  # runtime: nodejs10.x

profile: serverless-aws-admin

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
