service:
  name: serverless-typescript-call-mock-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

profile: serverless-aws-admin

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
